import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header/Header";
// import Provider from "./Provider";
import { ThemeProvider } from "next-themes";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Job Hunter | Let's Find Jobs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ThemeProvider defaultTheme='system' attribute="class">
          <div className="max-w-5xl mx-auto flex flex-col">
            <Header />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
